### ISSUE TITLE
新注册的用户登录不了，这个queryByHQL返回的是arraylist强制转换为user错误

### ISSUE THREAD

**Issue by lovingcowboy** [EnjoyError/forum#15]
public User getUserByUsername(String username) {
        String hql = "FROM User myUser WHERE myUser.username = :username";
        return (User) store.queryByHQL(hql, "username", username);
    }

**Comment by lingxiadeyidu** [comment]
谢谢反馈，确实有这个问题，已经在修改了，，，

**Comment by lingxiadeyidu** [comment]
确实有这个问题，，，

**Comment by EnjoyError** [comment]
已修复
